#!/usr/bin/env php
<?php
require_once dirname(__FILE__) . '/lib/class.LazyLoader.php';
Plugins::loadAll();
$args = CommandLineUtils::parseArgs($argv);

if (isset($args['h']) || isset($args['help'])) {
    //TODO Write help function.
}

if (!isset($args['glob']) || !isset($args['template']) || !isset($args['file'])) {
    echo 'Incorrect script usage. Please run php_docgen --help for more details.' . "\n";
    exit;
}

$glob = $args['glob'];
$template = $args['template'];
$output_file = $args['file'];

if (!file_exists($template)) {
    echo 'The template "' . $template . '" could not be found. Are you sure that' .
        ' you specified a valid path?' . "\n";
    exit;
}

$search = new CodeSearch();
$search->findClasses($glob);

// Add an init script if one is specified.
if (isset($args['init'])) {
    $search->addInitScript($args['init']);
}

$parser = new Parser($search->getClassList());
$parser->parseAllToFile($template, $output_file);

// Generate a toctree if the --toctree argument is passed.
if (isset($args['toctree'])) {
    $parser->generateTocTree(dirname($output_file) . 'index.rst');
}

?>
