#!/usr/bin/env php
<?php
// Require the lazy loader. This will auto load classes for you.
require_once dirname(__FILE__) . '/lib/class.LazyLoader.php';

// Parse the command line args into something more usable.
$args = CommandLineUtils::parseArgs($argv);

// Create the application.
$app = new Application($args);

$app->go();
?>
