#!/usr/bin/env php
<?php
$tu_path = '/home/sam/Dropbox/code/PHP/ThinkUp/';
$classes = array('__init__' => '/home/sam/Dropbox/code/PHP/ThinkUp/webapp/init.php');
$globs = array(
    'webapp/_lib/**/class.*.php',
    'webapp/_lib/**/interface.*.php'
);

foreach ($globs as $glob) {
    foreach (glob($tu_path . $glob) as $file) {
        $class_name = preg_replace('/(?:interface|class)\.(.+)\.php/', '$1' ,basename($file));
        $classes[$class_name] = $file;
    }
}
echo json_encode($classes);
?>
